### ISSUE TITLE
Example of OTR/Signal or some encryption library

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-reactnative-samples#157]
Hello,
Looking at the documentation on this page I see that it is possible to combine connectycube with some encryption protocols. However, this guide is written for vanilla JS. Is there any way to do the same approach in a React Native environment?
https://developers.connectycube.com/guides/end-to-end-encryption-otr

**Comment by DaveLomber** [comment]
Since OTR lib is written in JS - it should be possible to connect it to React Native.

Also, you may find useful to check this guide about implementing basic E2EE
https://soatok.blog/2020/11/14/going-bark-a-furrys-guide-to-end-to-end-encryption/

Despite this, 
we have plans to release OMEMO E2EE soon.

**Comment by ethanx94** [comment]
Hi @DaveLomber is OMEO still on the timeline or has it possibly been released? Would this be a server side enhancement or some change to an existing API?
I wanted to know before I hop into implementing this.

**Comment by DaveLomber** [comment]
@ethanx94 it's not released yet, 
we are still working on it, more actively than before 

Basically there will be some small changes to backend side.
I really hope there will be more updates on March and first alpha ver will go live
