### ISSUE TITLE
error 401 on create session

### ISSUE THREAD

**Issue by JhosepIslam** [ConnectyCube/connectycube-reactnative-samples#209]
After a period of non-use, an alert request failed with status code 401 appears and we detect that this message comes from its react-native-connectycube package.

We have Session expiration enabled in the configuration but it seems that it is not working, I hope you can help us detect the problem and solve it.

react-native-connectycube: 1.8.1
React Native: 0.61.5

**Comment by DaveLomber** [comment]
Are you following the session expiration guide?

https://developers.connectycube.com/js/authentication-and-users?id=session-expiration 

Please show your implementation, we have to review it

**Comment by JhosepIslam** [comment]
Yes, we follow the entire session expiration guide, in fact it has worked well for a long time, the problem started a few days ago

**Comment by JhosepIslam** [comment]
> Are you following the session expiration guide?
> 
> https://developers.connectycube.com/js/authentication-and-users?id=session-expiration
> 
> Please show your implementation, we have to review it

Yes, we follow the entire session expiration guide, in fact it has worked well for a long time, the problem started a few days ago

**Comment by JhosepIslam** [comment]
> Are you following the session expiration guide?
> 
> https://developers.connectycube.com/js/authentication-and-users?id=session-expiration
> 
> Please show your implementation, we have to review it

The implementation is exactly the same from the documentation and we cannot catch the error because it is generated in the node_modules package of connectycube

**Comment by JhosepIslam** [comment]
any idea that could be causing the bug?

**Comment by DaveLomber** [comment]
@JhosepIslam I suggest to perform more tests and see how this code works, especially - the following flow:

1) add the above code in your app to manage session expiration (if not already added)
2) then run the app, normally 
3) then,  from logs, get the current user's session token 
4)  then in parallel, using REST API, remove the session https://developers.connectycube.com/server/auth?id=destroy-session
5) then back to app and see how it behaves. Does the session expiration flow work well? If not - can you spot the issue?

**Comment by ethanx94** [comment]
Not to hijack this thread but I've been having issues as well. I'm continuing to use the config.json but I have done an object spread of a function to handle sessionExpired. Is this a valid approach? I've thrown breakpoints and log statements in but they don't seem to get hit either.

![image](https://user-images.githubusercontent.com/4449468/111395998-85065a80-8694-11eb-96fd-4ec734d7e00b.png)
![image](https://user-images.githubusercontent.com/4449468/111396012-8a63a500-8694-11eb-8a92-71e7cbe4b43d.png)

**Comment by DaveLomber** [comment]
@ethanx94 object spread for ConnectyCube config is not an issue at all 

Your code looks correct

Could you please do me a favour

Please enable logs (by passing `debug: { mode: 1 }`), e.g.

```
const CONFIG = {
  debug: { mode: 1 }, // enable DEBUG mode (mode 0 is logs off, mode 1 -> console.log())
};
ConnectyCube.init(CREDENTIALS, CONFIG);
```


and then post here the output at the tome when you expect a session expiration handler to be called

**Comment by ethanx94** [comment]
I think I have it worked out. I was using some old 2.0 version where the check for isExpiredSessionError was looking for a different server response. I don't have the 2.0 code anymore but the offender was here error.info.errors.base[0], it was checking against something else in the old versions.
![image](https://user-images.githubusercontent.com/4449468/111712097-5ec2f500-8823-11eb-8910-47722198cd26.png)

Additionally I had to create a session using parameters (possibly because I'm using external identity provider with firebase) and keep my refreshed token, as this error interrupts the signIn method that gets hit on automatic login and would cause the XMPP connect call to fail.

![image](https://user-images.githubusercontent.com/4449468/111712458-0d673580-8824-11eb-92b0-6835241dcd4c.png)

I made this reInit method because occasionally my credentials appear to be missing.
![image](https://user-images.githubusercontent.com/4449468/111712651-70f16300-8824-11eb-9e02-c1b32132208a.png)


(The following code is in the signIn method)
![image](https://user-images.githubusercontent.com/4449468/111712466-10622600-8824-11eb-8879-bd776eb4000d.png)

![image](https://user-images.githubusercontent.com/4449468/111713036-2de3bf80-8825-11eb-896b-f45fe6a3088c.png)

In general I think I'm running off some very old example code that I have changed a lot but I wanted to post here for reference in case others were experiencing the same issues.

The simple fix for most people would probably just be a quick
`npm i react-native-connectycube@latest`

**Comment by DaveLomber** [comment]
@ethanx94 much appreciated for the update and the solution 🥇

**Comment by ethanx94** [comment]
One more slight issue with this. The avatar links in all the User objects are still holding the old token as a query parameter. I think this can be changed in the getOccupants method in users-service.
Maybe some check to replace this token if it has been refreshed?

**Comment by DaveLomber** [comment]
@ethanx94 I highly recommend not to store a full url as avatar
Instead - store file uid and then build a full url on the flight using a helper ` const fileUrl = ConnectyCube.storage.privateUrl(fileUID);` like described in a file attachments section https://developers.connectycube.com/reactnative/messaging?id=attachments-photo-video

**Comment by ethanx94** [comment]
I think the issue here is that users are stored with their avatar URL's fully intact because of the model. When the token refreshes it would need to update all the users's avatar urls.
https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/models/user.js

My workaround for the time being is to just clear all users out of the store when the token gets refreshed, at the end of my on session expired handler. That way when getOccupants is called it creates a new user object for each user and builds up the proper urls. It's probably some additional network requests but it's not too taxing.
https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/services/users-service.js
