### ISSUE TITLE
Getting Echo and Noice when making Calls On Loudspeaker (Android 11)

### ISSUE THREAD

**Issue by codepoetryindia** [ConnectyCube/connectycube-reactnative-samples#247]

**Comment by ccvlad** [comment]
Hi @codepoetryindia 

Try this guide - https://developers.connectycube.com/reactnative/videocalling?id=echo-cancelation-issue-on-some-android-devices

We use [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc) lib in 'react-native-connectycube' SDK.

**Comment by codepoetryindia** [comment]
That is not proper documentation. Can you Please guide how to implement that code

**Comment by ccvlad** [comment]
This isn't our documentation. The link related to [react-native-webrtc issues](https://github.com/react-native-webrtc/react-native-webrtc/issues). I tried this method but it got worse for my device (Galaxy S20). So I prefer to use common echo cancelation that included in react-native-webrtc. Make sure that you have problem with devices specified in this issue. I am able to post the code, but it will take a while because I don't have it right now.

**Comment by codepoetryindia** [comment]
Thanks for your reply.

But I'm struggling too much on this. Please post the code till then I will wait

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
