### ISSUE TITLE
Chat messages are not delivered

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-reactnative-samples#298]
Hey folks,

Since yesterday, we are experiencing a odd behavior on the platform chat.

Messages are not delivered, we can see the WebSocket is connected BUT after sunmitting, the WS return a WS message:

```
<message from=\"1145643-1591@chat.connectycube.com\" type=\"error\" to=\"1156124-1591@chat.connectycube.com/2039927192-chat-17231\" xmlns=\"jabber:client\"><composing xmlns=\"http://jabber.org/protocol/chatstates\"/><error type=\"cancel\" code=\"503\"><service-unavailable xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"/><text xml:lang=\"en\" xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\">Service not available.</text></error></message>
```

any ideas of what's going on?

**Comment by DaveLomber** [comment]
@masmerino13 is it just about typing messages? or regular chat messages as well ?

**Comment by masmerino13** [comment]
@DaveLomber any help with it is very welcome, since we have some clients getting crazy because of the issue,

**Comment by mega4174** [comment]
> @masmerino13 is it just about typing messages? or regular chat messages as well ?

Hi dave,  We have many customer complaints since yesterday.  The problem is that the same user sends a message to another and it appears as if the message arrived. When you exit the chat and go back and check again, the message was not sent and is gone. that is, it disappears. We documented this to Garry via email. This happens with almost 60% of messages sent. That is, it is random, it does not always happen but it affects almost half of the messages sent.

**Comment by mega4174** [comment]
> @masmerino13 is it just about typing messages? or regular chat messages as well ?
We have documented this in several videos sent to Garry and Tanya that I hope you can watch.

**Comment by mega4174** [comment]
Hi @DaveLomber, we would greatly appreciate your help to give us an answer as soon as possible since many clients have been complaining about this inconvenience since yesterday and we are receiving multiple emails with complaints.

**Comment by mega4174** [comment]
> @masmerino13 is it just about typing messages? or regular chat messages as well ?



> @masmerino13 is it just about typing messages? or regular chat messages as well ?

Hi,@DaveLomber, we want to ask you to please let us know in what situation is the solution to the reported problem.

We are under great pressure due to the large number of emails we are receiving, complaints from our clients due to the communication platform not working properly.
This is affecting us a lot as we are losing users and we are also getting a lot of unsubscribes.

We appreciate your understanding and prompt solution to this issue.

Feel free to contact us if you need a username and password to test the website. Also if you need any information from us as our team is facing a permanent emergency due to this situation.

Sincerely

**Comment by DaveLomber** [comment]
Could someone confirm whether this issue is still actually? We will follow up
